baseURL = "http://localhost:1313"
languageCode = "en"
title = "Linting"
theme = "hugo-nuo"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true

# Initial site menu, you can extend menu with content.
  [[menu.main]]
    name = "Home"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Atom"
    weight = 2
    identifier = "atom"
    url = "/post/atom"
  [[menu.main]]
    name = "Sublime Text"
    weight = 3
    identifier = "sublimetext"
    url = "/post/sublime"
  [[menu.main]]
    name = "Visual Studio Code"
    weight = 4
    identifier = "vscode"
    url = "/post/vsCode"
  [[menu.main]]
    name = "ESLint Configuration"
    weight = 5
    identifier = "eslint"
    url = "/post/esLint"

# Add your own params here
[params]
  author = ""
  avatar = "/images/eslint.svg"
  seotitle = "Hugo Blog (SEO Version)"
  subtitle = "Improves your code quality"
  description = "Hugo is one of the most popular open-source static site generators. With its amazing speed and flexibility, Hugo makes building websites fun again."
  paginate = 10
  custom_css = ["css/style.css"]
